version: 3

tasks:
  install:
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
    - deactivate
  
  start:
    - source .venv/bin/activate
    - python3 main.py
    - deactivate